name: CI - linter & tests

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter and tests
        run: |
          make build
          make check-code
