name: CD - deploy to DockerHub

on:
  push:
    branches: [master, main, refactor/migrate-to-pytorch-and-simplify-architecture]

jobs:
  deploy:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Docker build, tag & push
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_REPO: vad
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build . -t $DOCKER_USER/$DOCKER_REPO:$IMAGE_TAG
          docker push $DOCKER_USER/$DOCKER_REPO:$IMAGE_TAG
          docker tag $DOCKER_USER/$DOCKER_REPO:$IMAGE_TAG $DOCKER_USER/$DOCKER_REPO:latest
          docker push $DOCKER_USER/$DOCKER_REPO:latest
