
name: CI - linters & tests

on: [ push ]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run linter and tests
        run: |
          make check-test-docker
