
name: CI - linters & tests

on: [ push ]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Builder docker image, run linter & tests
      run: |
        make check-test-docker
